
services:
  web:
    build: .
    container_name: media-parser-backend
    restart: always
    ports:
      - "8051:8051"
    volumes:
      # 将宿主机上的日志、静态视频目录映射，以便容器删除和重建时不丢失数据或便于排查问题
      - ./static/videos:/app/static/videos
      - ./logs:/app/logs
    # 设置容器内的时区为本地时区
    environment:
      - TZ=Asia/Shanghai
