from . import login
from . import ranking
from . import upload_userinfo
from . import refresh_video
from . import upload_record
from . import download
from . import upload_score
from . import records
from . import parse
from . import admin
from . import share
