from .login import bp as login
from .ranking import bp as ranking
from .upload_userinfo import bp as upload_userinfo
from .refresh_video import bp as refresh_video
from .upload_record import bp as upload_record
from .download import bp as download
from .upload_score import bp as upload_score
from .records import bp as records
from .parse import bp as parse
from .admin import bp as admin
